#!/bin/sh

set -e

# Install Homebrew
if [ ! -f /opt/homebrew/bin/brew ]; then
    echo "Installing Homebrew..."
    # https://brew.sh/#install
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Create ~/Developer directory
if [ ! -d ~/Developer ]; then
    echo "Creating ~/Developer directory..."
    mkdir ~/Developer
fi

# Clone dotfiles repo
if [ ! -d ~/Developer/dotfiles ]; then
    echo "Cloning dotfiles repo..."
    cd ~/Developer
    git clone git@github.com:kijikunnn/dotfiles.git
fi

# Install Homebrew packages
brew bundle -v --file=~/Developer/dotfiles/Brewfile

# Change Default shell to fish
if [ "$SHELL" != "/opt/homebrew/bin/fish" ]; then
    echo "Changing default shell to fish..."
    echo "/opt/homebrew/bin/fish" | sudo tee -a /etc/shells
    chsh -s /opt/homebrew/bin/fish
fi

